const movementTypes = [
  'WAREHOUSE',
  'WAREHOUSE_TO_SITE',
  'SITE_TO_WAREHOUSE',
  'PROJECT_SITE',
  'SITE_TO_SITE',
  'OTHER',
];

export const MovementLogSchemas = {
  MovementLogObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      code: { type: 'string', example: 'MVL-001' },
      movementType: { type: 'string', enum: movementTypes },
      assetType: { type: 'string', enum: ['VEHICLE', 'MACHINERY'] },
      vehicleId: { type: 'string', format: 'uuid', nullable: true },
      machineryId: { type: 'string', format: 'uuid', nullable: true },
      projectId: { type: 'string', format: 'uuid', nullable: true },
      fromLocation: { type: 'string', nullable: true },
      toLocation: { type: 'string', nullable: true },
      startDateTime: { type: 'string', format: 'date-time' },
      endDateTime: { type: 'string', format: 'date-time' },
      hours: { type: 'number', example: 10.5 },
      startMeterReading: { type: 'number', nullable: true, example: 800 },
      endMeterReading: { type: 'number', nullable: true, example: 814 },
      meterUsage: { type: 'number', nullable: true, example: 14 },
      notes: { type: 'string', nullable: true },
      vehicle: { type: 'object', nullable: true },
      machinery: { type: 'object', nullable: true },
      project: { type: 'object', nullable: true },
      status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'] },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  CreateMovementLogBody: {
    type: 'object',
    required: [
      'code',
      'movementType',
      'assetType',
      'startDateTime',
      'endDateTime',
    ],
    properties: {
      code: { type: 'string', example: 'MVL-001' },
      movementType: { type: 'string', enum: movementTypes },
      assetType: { type: 'string', enum: ['VEHICLE', 'MACHINERY'] },
      vehicleId: { type: 'string', format: 'uuid', nullable: true },
      machineryId: { type: 'string', format: 'uuid', nullable: true },
      projectId: { type: 'string', format: 'uuid', nullable: true },
      fromLocation: { type: 'string', nullable: true },
      toLocation: { type: 'string', nullable: true },
      startDateTime: { type: 'string', format: 'date-time' },
      endDateTime: { type: 'string', format: 'date-time' },
      startMeterReading: { type: 'number', minimum: 0, nullable: true },
      endMeterReading: { type: 'number', minimum: 0, nullable: true },
      notes: { type: 'string', nullable: true },
      status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'] },
    },
  },
};
