export const PaymentRequestSchemas = {
  CreatePaymentRequestBody: {
    type: 'object',
    required: [
      'type',
      'vendorId',
      'projectId',
      'referenceNumber',
      'tds',
      'grossAmount',
      'netPayable',
    ],
    properties: {
      date: {
        type: 'string',
        format: 'date-time',
        description: 'Payment request date (defaults to now)',
        example: '2026-06-02T00:00:00.000Z',
      },
      type: { type: 'string', example: 'ADVANCE' },
      vendorId: {
        type: 'string',
        format: 'uuid',
        description: 'VendorProductPricing ID',
      },
      projectId: { type: 'string', format: 'uuid' },
      referenceNumber: { type: 'string', example: 'INV-2026-001' },
      tds: { type: 'number', minimum: 0, example: 5.0 },
      grossAmount: { type: 'number', minimum: 0, example: 50000 },
      netPayable: { type: 'number', minimum: 0, example: 47500 },
      notes: { type: 'string', example: 'Advance payment for materials' },
      paymentStatus: {
        type: 'string',
        enum: ['PENDING', 'APPROVED', 'PAID'],
        default: 'PENDING',
      },
      status: {
        type: 'string',
        enum: ['ACTIVE', 'INACTIVE'],
        default: 'ACTIVE',
      },
    },
  },
  UpdatePaymentRequestBody: {
    type: 'object',
    properties: {
      date: { type: 'string', format: 'date-time' },
      type: { type: 'string', example: 'FINAL' },
      vendorId: { type: 'string', format: 'uuid' },
      projectId: { type: 'string', format: 'uuid' },
      referenceNumber: { type: 'string', example: 'INV-2026-002' },
      tds: { type: 'number', minimum: 0 },
      grossAmount: { type: 'number', minimum: 0 },
      netPayable: { type: 'number', minimum: 0 },
      notes: { type: 'string' },
      paymentStatus: {
        type: 'string',
        enum: ['PENDING', 'APPROVED', 'PAID'],
      },
      status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'] },
    },
  },
  PaymentRequestObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      code: { type: 'string', example: 'PR-02062026040744123' },
      date: { type: 'string', format: 'date-time' },
      type: { type: 'string', example: 'ADVANCE' },
      vendorId: { type: 'string', format: 'uuid' },
      vendor: { type: 'object', description: 'VendorProductPricing details' },
      projectId: { type: 'string', format: 'uuid' },
      project: { type: 'object', description: 'Project details' },
      referenceNumber: { type: 'string', example: 'INV-2026-001' },
      tds: { type: 'number', example: 5.0 },
      grossAmount: { type: 'number', example: 50000 },
      netPayable: { type: 'number', example: 47500 },
      notes: { type: 'string', example: 'Advance payment for materials' },
      requestedBy: { type: 'string', format: 'uuid' },
      requestedUser: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          email: { type: 'string', format: 'email' },
        },
      },
      paymentStatus: {
        type: 'string',
        enum: ['PENDING', 'APPROVED', 'PAID'],
        example: 'PENDING',
      },
      domainId: { type: 'string', format: 'uuid' },
      status: { type: 'string', example: 'ACTIVE' },
      isDeleted: { type: 'boolean', example: false },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
};
