const localizedObject = {
  type: 'object',
  additionalProperties: true,
  example: { en: 'Sample name' },
};

const activeStatus = {
  type: 'string',
  enum: ['ACTIVE', 'INACTIVE'],
  example: 'ACTIVE',
  description: 'Allowed values: ACTIVE, INACTIVE',
};

const taskStatus = {
  type: 'string',
  example: 'PENDING',
  description:
    'Task workflow status. Common values: PENDING, IN_PROGRESS, COMPLETED.',
};

const dateField = {
  type: 'string',
  nullable: true,
  example: '2026-05-18',
};

const idOrIds = {
  oneOf: [
    { type: 'string', format: 'uuid' },
    {
      type: 'array',
      minItems: 1,
      items: { type: 'string', format: 'uuid' },
    },
  ],
};

export const ProjectSchemas = {
  ProjectObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      name: localizedObject,
      description: { type: 'string', nullable: true, example: 'Site work' },
      budget: { type: 'number', example: 100000 },
      spent: { type: 'number', example: 25000 },
      expectedStartDate: dateField,
      expectedEndDate: dateField,
      actualStartDate: dateField,
      actualEndDate: dateField,
      totalDelayInDays: { type: 'number', example: 13 },
      locationId: { type: 'string', format: 'uuid' },
      domainId: { type: 'string', format: 'uuid' },
      status: activeStatus,
      projectStages: {
        type: 'array',
        items: { $ref: '#/components/schemas/ProjectStageObject' },
      },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  ProjectAnalyticsObject: {
    type: 'object',
    properties: {
      projectCounts: {
        type: 'object',
        properties: {
          total: { type: 'integer', example: 20 },
          inProgress: { type: 'integer', example: 8 },
          completed: { type: 'integer', example: 5 },
        },
      },
      budget: {
        type: 'object',
        properties: {
          total: { type: 'number', example: 1000000 },
          spent: { type: 'number', example: 450000 },
        },
      },
      inProgressProjectAnalytics: {
        type: 'object',
        properties: {
          taskDelayCount: { type: 'integer', example: 12 },
          taskDelayDuration: { type: 'number', example: 35 },
          taskSubmissionCount: { type: 'integer', example: 40 },
          taskApprovalCount: { type: 'integer', example: 25 },
        },
      },
    },
  },
  CreateProjectBody: {
    type: 'object',
    required: ['name', 'budget', 'locationId'],
    properties: {
      name: localizedObject,
      description: { type: 'string', nullable: true, example: 'Site work' },
      budget: { type: 'number', minimum: 0, example: 100000 },
      spent: { type: 'number', minimum: 0, example: 0 },
      expectedStartDate: { type: 'string', example: '2026-05-18' },
      expectedEndDate: { type: 'string', example: '2026-08-18' },
      locationId: { type: 'string', format: 'uuid' },
      status: activeStatus,
      projectStages: {
        type: 'array',
        items: { $ref: '#/components/schemas/CreateProjectStageInlineBody' },
      },
    },
  },
  UpdateProjectBody: {
    type: 'object',
    properties: {
      name: localizedObject,
      description: { type: 'string', nullable: true, example: 'Site work' },
      budget: { type: 'number', minimum: 0 },
      spent: { type: 'number', minimum: 0 },
      actualStartDate: dateField,
      actualEndDate: dateField,
      locationId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  CreateProjectStageInlineBody: {
    type: 'object',
    required: ['name'],
    properties: {
      name: localizedObject,
      description: { type: 'string', nullable: true, example: 'Foundation' },
      progress: { type: 'number', minimum: 0, nullable: true, example: 0 },
      expectedStartDate: { type: 'string', example: '2026-05-18' },
      expectedEndDate: { type: 'string', example: '2026-06-18' },
      status: activeStatus,
    },
  },
  ProjectStageObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      name: localizedObject,
      description: { type: 'string', nullable: true, example: 'Foundation' },
      progress: { type: 'number', example: 35 },
      expectedStartDate: dateField,
      expectedEndDate: dateField,
      actualStartDate: dateField,
      actualEndDate: dateField,
      totalDelayInDays: { type: 'number', example: 5 },
      projectId: { type: 'string', format: 'uuid' },
      domainId: { type: 'string', format: 'uuid' },
      status: activeStatus,
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  CreateDomainProjectStageBody: {
    type: 'object',
    required: ['name', 'domainId'],
    properties: {
      name: localizedObject,
      description: { type: 'string', nullable: true, example: 'Foundation' },
      progress: { type: 'number', minimum: 0, nullable: true, example: 0 },
      expectedStartDate: { type: 'string', example: '2026-05-18' },
      expectedEndDate: { type: 'string', example: '2026-06-18' },
      projectId: { type: 'string', format: 'uuid', nullable: true },
      domainId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  CreateProjectStageBody: {
    type: 'object',
    required: ['name'],
    properties: {
      name: localizedObject,
      description: { type: 'string', nullable: true, example: 'Foundation' },
      progress: { type: 'number', minimum: 0, nullable: true, example: 0 },
      expectedStartDate: { type: 'string', example: '2026-05-18' },
      expectedEndDate: { type: 'string', example: '2026-06-18' },
      status: activeStatus,
    },
  },
  UpdateProjectStageBody: {
    type: 'object',
    properties: {
      name: localizedObject,
      description: { type: 'string', nullable: true, example: 'Foundation' },
      progress: { type: 'number', minimum: 0, nullable: true, example: 35 },
      actualStartDate: dateField,
      actualEndDate: dateField,
      status: activeStatus,
    },
  },
  ProjectTaskObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      name: localizedObject,
      assignee: {
        type: 'string',
        format: 'uuid',
        nullable: true,
        description: 'User ID assigned to this task.',
      },
      plannedStartDate: dateField,
      plannedEndDate: dateField,
      actualStartDate: dateField,
      actualEndDate: dateField,
      taskStatus,
      taskProgress: { type: 'number', example: 20 },
      totalDelayInDays: { type: 'number', example: 0 },
      requiredApproval: { type: 'boolean', example: false },
      lastApprovedDeadline: dateField,
      projectBatchCode: {
        type: 'string',
        nullable: true,
        example: 'BATCH-001',
      },
      stageId: { type: 'string', format: 'uuid' },
      projectId: { type: 'string', format: 'uuid' },
      domainId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  ProjectTaskImageInput: {
    type: 'object',
    required: ['imageId'],
    properties: {
      imageId: {
        type: 'string',
        format: 'uuid',
        description: 'Media ID uploaded through media API.',
      },
      description: {
        type: 'string',
        nullable: true,
        example: 'Before work photo',
      },
    },
  },
  CreateDomainProjectTaskBody: {
    type: 'object',
    required: ['name', 'stageId', 'projectId', 'domainId'],
    properties: {
      name: localizedObject,
      assignee: {
        type: 'string',
        format: 'uuid',
        nullable: true,
        description: 'User ID assigned to this task.',
      },
      plannedStartDate: dateField,
      plannedEndDate: dateField,
      actualStartDate: dateField,
      actualEndDate: dateField,
      taskStatus,
      taskProgress: { type: 'number', minimum: 0, maximum: 100, example: 0 },
      totalDelayInDays: { type: 'number', minimum: 0, example: 0 },
      requiredApproval: { type: 'boolean', nullable: true, example: false },
      lastApprovedDeadline: dateField,
      projectBatchCode: {
        type: 'string',
        nullable: true,
        example: 'BATCH-001',
      },
      stageId: { type: 'string', format: 'uuid' },
      projectId: { type: 'string', format: 'uuid' },
      domainId: { type: 'string', format: 'uuid' },
      status: activeStatus,
      images: {
        type: 'array',
        items: { $ref: '#/components/schemas/ProjectTaskImageInput' },
      },
    },
  },
  CreateProjectTaskBody: {
    type: 'object',
    required: ['name', 'stageId', 'projectId'],
    properties: {
      name: localizedObject,
      assignee: {
        type: 'string',
        format: 'uuid',
        nullable: true,
        description: 'User ID assigned to this task.',
      },
      plannedStartDate: dateField,
      plannedEndDate: dateField,
      actualStartDate: dateField,
      actualEndDate: dateField,
      taskStatus,
      taskProgress: { type: 'number', minimum: 0, maximum: 100, example: 0 },
      totalDelayInDays: { type: 'number', minimum: 0, example: 0 },
      requiredApproval: { type: 'boolean', nullable: true, example: false },
      lastApprovedDeadline: dateField,
      projectBatchCode: {
        type: 'string',
        nullable: true,
        example: 'BATCH-001',
      },
      stageId: { type: 'string', format: 'uuid' },
      projectId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  DomainUpdateProjectTaskBody: {
    type: 'object',
    properties: {
      name: localizedObject,
      assignee: { type: 'string', format: 'uuid', nullable: true },
      plannedStartDate: dateField,
      plannedEndDate: dateField,
      actualStartDate: dateField,
      actualEndDate: dateField,
      taskStatus,
      taskProgress: { type: 'number', minimum: 0, maximum: 100, example: 40 },
      totalDelayInDays: { type: 'number', minimum: 0, example: 2 },
      requiredApproval: { type: 'boolean', nullable: true, example: true },
      lastApprovedDeadline: dateField,
      projectBatchCode: {
        type: 'string',
        nullable: true,
        example: 'BATCH-001',
      },
      status: activeStatus,
      images: {
        type: 'array',
        description:
          'Optional images to append to the task. Existing images are not removed.',
        items: { $ref: '#/components/schemas/ProjectTaskImageInput' },
      },
    },
  },
  UpdateProjectTaskBody: {
    type: 'object',
    properties: {
      name: localizedObject,
      assignee: { type: 'string', format: 'uuid', nullable: true },
      plannedStartDate: dateField,
      plannedEndDate: dateField,
      actualStartDate: dateField,
      actualEndDate: dateField,
      taskStatus,
      taskProgress: { type: 'number', minimum: 0, maximum: 100, example: 40 },
      totalDelayInDays: { type: 'number', minimum: 0, example: 2 },
      requiredApproval: { type: 'boolean', nullable: true, example: true },
      lastApprovedDeadline: dateField,
      projectBatchCode: {
        type: 'string',
        nullable: true,
        example: 'BATCH-001',
      },
      status: activeStatus,
    },
  },
  ProjectTaskApprovalBody: {
    type: 'object',
    required: ['ids', 'approvalState'],
    properties: {
      ids: idOrIds,
      approvalState: {
        type: 'string',
        enum: ['APPROVED', 'REJECTED'],
        example: 'APPROVED',
      },
    },
  },
  ProjectTaskDelayObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      taskId: { type: 'string', format: 'uuid' },
      requestedDelayInDays: { type: 'number', example: 2 },
      delayReason: {
        type: 'string',
        example: 'Material delivery was delayed.',
        description: 'Single language delay reason.',
      },
      requestApproved: {
        type: 'boolean',
        example: false,
        description: 'false means pending, true means approved.',
      },
      approvalState: {
        type: 'string',
        enum: ['PENDING', 'APPROVED', 'REJECTED'],
        example: 'PENDING',
        description:
          'Computed state. PENDING when requestApproved is false and requestApprovalTime is empty.',
      },
      requestApprovalTime: { type: 'string', nullable: true },
      stageId: { type: 'string', format: 'uuid' },
      projectId: { type: 'string', format: 'uuid' },
      domainId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  CreateDomainProjectTaskDelayBody: {
    type: 'object',
    required: [
      'taskId',
      'requestedDelayInDays',
      'delayReason',
      'stageId',
      'projectId',
      'domainId',
    ],
    properties: {
      taskId: { type: 'string', format: 'uuid' },
      requestedDelayInDays: { type: 'number', minimum: 0, example: 2 },
      delayReason: {
        type: 'string',
        example: 'Material delivery was delayed.',
        description: 'Single language delay reason.',
      },
      requestApproved: {
        type: 'boolean',
        example: false,
        description: 'Allowed values: false = PENDING, true = APPROVED.',
      },
      requestApprovalTime: { type: 'string', nullable: true },
      stageId: { type: 'string', format: 'uuid' },
      projectId: { type: 'string', format: 'uuid' },
      domainId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  CreateProjectTaskDelayBody: {
    type: 'object',
    required: [
      'taskId',
      'requestedDelayInDays',
      'delayReason',
      'stageId',
      'projectId',
    ],
    properties: {
      taskId: { type: 'string', format: 'uuid' },
      requestedDelayInDays: { type: 'number', minimum: 0, example: 2 },
      delayReason: {
        type: 'string',
        example: 'Material delivery was delayed.',
        description: 'Single language delay reason.',
      },
      requestApproved: { type: 'boolean', nullable: true, example: false },
      requestApprovalTime: { type: 'string', nullable: true },
      stageId: { type: 'string', format: 'uuid' },
      projectId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  UpdateProjectTaskDelayBody: {
    type: 'object',
    properties: {
      requestedDelayInDays: { type: 'number', minimum: 0, example: 2 },
      delayReason: {
        type: 'string',
        example: 'Material delivery was delayed.',
      },
      requestApproved: { type: 'boolean', nullable: true, example: false },
      requestApprovalTime: { type: 'string', nullable: true },
      status: activeStatus,
    },
  },
  ProjectTaskActionBody: {
    type: 'object',
    required: ['ids'],
    properties: {
      ids: idOrIds,
      action: {
        type: 'string',
        enum: ['APPROVED', 'REJECTED', 'APPROVAL', 'REJECTION'],
        example: 'APPROVED',
      },
      approvalState: {
        type: 'string',
        enum: ['APPROVED', 'REJECTED', 'APPROVAL', 'REJECTION'],
        example: 'APPROVED',
      },
    },
  },
  ProjectTaskSubmissionObject: {
    type: 'object',
    additionalProperties: true,
    properties: {
      taskId: { type: 'string', format: 'uuid' },
      userId: { type: 'string', format: 'uuid' },
      actualEndDate: { type: 'string', example: '2026-05-25' },
      taskProgress: { type: 'number', example: 100 },
      approvalState: {
        type: 'string',
        enum: ['PENDING', 'APPROVED', 'REJECTED'],
        example: 'PENDING',
      },
    },
  },
  SubmitProjectTaskBody: {
    type: 'object',
    required: ['taskId', 'userId', 'actualEndDate'],
    properties: {
      taskId: { type: 'string', format: 'uuid' },
      userId: { type: 'string', format: 'uuid' },
      actualEndDate: { type: 'string', example: '2026-05-25' },
      taskProgress: { type: 'number', minimum: 0, maximum: 100, example: 100 },
      images: {
        type: 'array',
        items: {
          type: 'object',
          required: ['imageUrl'],
          properties: {
            imageId: { type: 'string', format: 'uuid' },
            imageUrl: { type: 'string', example: 'https://example.com/a.jpg' },
            description: { type: 'string', nullable: true },
          },
        },
      },
    },
  },
  UserSubmitTaskBody: {
    type: 'object',
    required: ['actualEndDate'],
    properties: {
      actualEndDate: { type: 'string', example: '2026-05-25' },
      taskProgress: { type: 'number', minimum: 0, maximum: 100, example: 100 },
      notes: { type: 'string', example: 'Completed shuttering work.' },
      images: {
        type: 'array',
        items: {
          type: 'object',
          required: ['imageUrl'],
          properties: {
            imageUrl: { type: 'string', example: 'https://example.com/a.jpg' },
            description: { type: 'string', nullable: true },
          },
        },
      },
    },
  },
  ProjectTaskImageObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      imageId: { type: 'string', format: 'uuid' },
      imageUrl: { type: 'string', example: 'https://example.com/a.jpg' },
      description: { type: 'string', nullable: true },
      taskId: { type: 'string', format: 'uuid' },
      projectId: { type: 'string', format: 'uuid' },
      domainId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  CreateProjectTaskImageBody: {
    type: 'object',
    required: ['imageId', 'taskId'],
    properties: {
      imageId: { type: 'string', format: 'uuid' },
      description: { type: 'string', nullable: true },
      taskId: { type: 'string', format: 'uuid' },
    },
  },
  ProjectUserAssignmentObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      projectId: { type: 'string', format: 'uuid' },
      userId: { type: 'string', format: 'uuid' },
      startDate: { type: 'string', example: '2026-05-18' },
      endDate: { type: 'string', example: '2026-06-18' },
      dailyWorkingHours: { type: 'number', example: 8 },
      dayCharge: { type: 'number', example: 1500 },
      notes: { type: 'string', nullable: true },
      status: activeStatus,
    },
  },
  CreateProjectUserAssignmentBody: {
    type: 'array',
    minItems: 1,
    items: {
      type: 'object',
      required: [
        'projectId',
        'userId',
        'startDate',
        'endDate',
        'dailyWorkingHours',
        'dayCharge',
      ],
      properties: {
        projectId: { type: 'string', format: 'uuid' },
        userId: { type: 'string', format: 'uuid' },
        startDate: { type: 'string', example: '2026-05-18' },
        endDate: { type: 'string', example: '2026-06-18' },
        dailyWorkingHours: { type: 'number', minimum: 0, example: 8 },
        dayCharge: { type: 'number', minimum: 0, example: 1500 },
        notes: { type: 'string', nullable: true },
        status: activeStatus,
      },
    },
  },
  UpdateProjectUserAssignmentBody: {
    type: 'object',
    properties: {
      startDate: { type: 'string', example: '2026-05-18' },
      endDate: { type: 'string', example: '2026-06-18' },
      dailyWorkingHours: { type: 'number', minimum: 0, example: 8 },
      dayCharge: { type: 'number', minimum: 0, example: 1500 },
      notes: { type: 'string', nullable: true },
      status: activeStatus,
    },
  },
  ProjectUserDailyLogObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      date: { type: 'string', example: '2026-05-18' },
      projectId: { type: 'string', format: 'uuid' },
      userId: { type: 'string', format: 'uuid' },
      startTime: { type: 'string', example: '09:00' },
      endTime: { type: 'string', example: '18:00' },
      totalWorkingHours: { type: 'number', example: 8 },
      dayCharge: { type: 'number', example: 1500 },
      notes: { type: 'string', nullable: true },
      status: activeStatus,
    },
  },
  CreateProjectUserDailyLogBody: {
    type: 'array',
    minItems: 1,
    items: {
      type: 'object',
      required: [
        'date',
        'projectId',
        'userId',
        'startTime',
        'endTime',
        'dayCharge',
      ],
      properties: {
        date: { type: 'string', example: '2026-05-18' },
        projectId: { type: 'string', format: 'uuid' },
        userId: { type: 'string', format: 'uuid' },
        startTime: { type: 'string', example: '09:00' },
        endTime: { type: 'string', example: '18:00' },
        totalWorkingHours: { type: 'number', minimum: 0, example: 8 },
        dayCharge: { type: 'number', minimum: 0, example: 1500 },
        notes: { type: 'string', nullable: true },
        status: activeStatus,
      },
    },
  },
  UpdateProjectUserDailyLogBody: {
    type: 'object',
    properties: {
      date: { type: 'string', example: '2026-05-18' },
      startTime: { type: 'string', example: '09:00' },
      endTime: { type: 'string', example: '18:00' },
      totalWorkingHours: { type: 'number', minimum: 0, example: 8 },
      dayCharge: { type: 'number', minimum: 0, example: 1500 },
      notes: { type: 'string', nullable: true },
      status: activeStatus,
    },
  },
  MachineryObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      code: { type: 'string', example: 'MCH-001' },
      type: localizedObject,
      expectedLitrePerHour: { type: 'number', example: 12 },
      projectId: { type: 'string', format: 'uuid' },
      project: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: localizedObject,
          code: { type: 'string', example: 'PRJ-001' },
        },
      },
      domainId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  CreateMachineryBody: {
    type: 'object',
    required: ['code', 'type', 'projectId'],
    properties: {
      code: { type: 'string', example: 'MCH-001' },
      type: { type: 'string', example: 'Excavator' },
      expectedLitrePerHour: { type: 'number', minimum: 0, example: 12 },
      projectId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  UpdateMachineryBody: {
    type: 'object',
    properties: {
      code: { type: 'string', example: 'MCH-001' },
      type: { type: 'string', example: 'Excavator' },
      expectedLitrePerHour: { type: 'number', minimum: 0, example: 12 },
      status: activeStatus,
    },
  },
  MachineReadingObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      date: { type: 'string', example: '2026-05-18' },
      refillFuelStock: { type: 'number', example: 100 },
      currentMachineReading: { type: 'number', example: 1500 },
      closingFuelStock: { type: 'number', example: 80 },
      fuelRefillQuantity: { type: 'number', example: 20 },
      machineStartTime: { type: 'string', example: '09:00' },
      machineEndTime: { type: 'string', example: '18:00' },
      projectId: { type: 'string', format: 'uuid' },
      status: { type: 'string', example: 'ACTIVE' },
    },
  },
  CreateMachineReadingBody: {
    type: 'object',
    required: ['date', 'machineStartTime', 'projectId'],
    properties: {
      date: { type: 'string', example: '2026-05-18' },
      refillFuelStock: { type: 'number', minimum: 0, example: 100 },
      currentMachineReading: { type: 'number', minimum: 0, example: 1500 },
      fuelRefillQuantity: { type: 'number', minimum: 0, example: 20 },
      machineStartTime: { type: 'string', example: '09:00' },
      projectId: { type: 'string', format: 'uuid' },
      status: activeStatus,
    },
  },
  UpdateMachineReadingBody: {
    type: 'object',
    required: ['closingFuelStock', 'machineEndTime'],
    properties: {
      closingFuelStock: { type: 'number', minimum: 0, example: 80 },
      fuelRefillQuantity: { type: 'number', minimum: 0, example: 20 },
      machineEndTime: { type: 'string', example: '18:00' },
      status: activeStatus,
    },
  },
  EndMachineReadingBody: {
    type: 'object',
    required: ['machineEndTime'],
    properties: {
      machineEndTime: { type: 'string', example: '18:00' },
    },
  },
  CurrencyObject: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      name: { type: 'object', example: { en: 'US Dollar' } },
      symbol: { type: 'string', example: '$' },
      flag: { type: 'string', example: 'https://flagcdn.com/w40/us.png' },
      status: { type: 'string', example: 'active' },
    },
  },
  UserCurrencyObject: {
    type: 'object',
    properties: {
      userRelationalId: {
        type: 'string',
        format: 'uuid',
        description: 'Currency ID exposed for the user module response.',
      },
      name: { type: 'string', example: 'US Dollar' },
      code: { type: 'string', example: 'DOLLAR' },
      symbol: { type: 'string', example: '$' },
      flag: { type: 'string', example: 'https://flagcdn.com/w40/us.png' },
      status: { type: 'string', example: 'active' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
};
