export const VehicleSchemas = {
  CreateVehicleBody: {
    type: 'object',
    required: ['numberPlate'],
    properties: {
      numberPlate: { type: 'string', example: 'MH-12-AB-1234' },
      vehicleType: { type: 'string', example: 'TRUCK' },
      loadCapacity: { type: 'number', example: 5000 },
      loadCapacityUomId: { type: 'string', format: 'uuid' },
      alertLoadThreshold: { type: 'number', example: 4500 },
    },
  },
  VehicleStatsResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string', example: 'Vehicle stats retrieved' },
      data: {
        type: 'object',
        properties: {
          totalVehicles: { type: 'integer', example: 12 },
          activeVehicles: { type: 'integer', example: 10 },
          inactiveVehicles: { type: 'integer', example: 2 },
          totalLoadCapacity: { type: 'number', example: 45000 },
          vehiclesByType: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                vehicleType: { type: 'string', example: 'TRUCK' },
                count: { type: 'integer', example: 8 },
              },
            },
          },
        },
      },
    },
  },
  VehicleListResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string', example: 'Vehicles retrieved' },
      pagination: {
        type: 'object',
        properties: {
          currentCount: { type: 'integer', example: 10 },
          totalCount: { type: 'integer', example: 12 },
          offset: { type: 'integer', example: 0 },
          limit: { type: 'integer', example: 10 },
        },
      },
      data: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            numberPlate: { type: 'string', example: 'MH-12-AB-1234' },
            vehicleType: { type: 'string', example: 'TRUCK' },
            loadCapacity: { type: 'number', example: 5000 },
            alertLoadThreshold: { type: 'number', example: 4500 },
            status: { type: 'string', example: 'active' },
            loadCapacityUom: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'string', format: 'uuid' },
                displayName: { type: 'object', example: { en: 'Kilogram' } },
                code: { type: 'string', example: 'KG' },
              },
            },
            latestSchedule: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'string', format: 'uuid' },
                code: { type: 'string', example: 'JS-001' },
                driverName: { type: 'string', example: 'Ramesh' },
                startLocation: { type: 'string', example: 'Quarry A' },
                endLocation: { type: 'string', example: 'Site B' },
                distance: { type: 'number', example: 120 },
                loadedQuantity: { type: 'number', example: 4200 },
                loadedAt: { type: 'string', format: 'date-time' },
                loadingStatus: { type: 'string', example: 'LOADED' },
                expectedFuelValue: { type: 'number', example: 45 },
                date: { type: 'string', format: 'date-time' },
              },
            },
            latestDispatch: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'string', format: 'uuid' },
                code: { type: 'string', example: 'DSP-042' },
                journeyStatus: { type: 'string', example: 'IN_TRANSIT' },
                journeyStatusUpdatedAt: { type: 'string', format: 'date-time' },
                loadingStatus: { type: 'string', example: 'LOADED' },
                loadedQuantity: { type: 'number', example: 4200 },
                actualFuelValue: { type: 'number', example: 48 },
                expectedFuelValue: { type: 'number', example: 45 },
              },
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
      },
    },
  },
  VehicleDetailResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string', example: 'Vehicles retrieved' },
      data: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          numberPlate: { type: 'string', example: 'MH-12-AB-1234' },
          vehicleType: { type: 'string', example: 'TRUCK' },
          loadCapacity: { type: 'number', example: 5000 },
          alertLoadThreshold: { type: 'number', example: 4500 },
          status: { type: 'string', example: 'active' },
          loadCapacityUom: { type: 'object', nullable: true },
          journeySchedules: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string', format: 'uuid' },
                code: { type: 'string', example: 'JS-001' },
                description: { type: 'string', nullable: true },
                driverName: { type: 'string', example: 'Ramesh' },
                startLocation: { type: 'string', example: 'Quarry A' },
                endLocation: { type: 'string', example: 'Site B' },
                distance: { type: 'number', example: 120 },
                average: { type: 'number', example: 35 },
                loadedQuantity: { type: 'number', example: 4200 },
                loadedAt: { type: 'string', format: 'date-time' },
                loadingStatus: { type: 'string', example: 'LOADED' },
                expectedFuelValue: { type: 'number', example: 45 },
                fuelAlertThreshold: { type: 'number', example: 50 },
                date: { type: 'string', format: 'date-time' },
                status: { type: 'string', example: 'active' },
                createdAt: { type: 'string', format: 'date-time' },
              },
            },
          },
          dispatches: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string', format: 'uuid' },
                code: { type: 'string', example: 'DSP-042' },
                description: { type: 'string', nullable: true },
                driverName: { type: 'string', example: 'Ramesh' },
                startLocation: { type: 'string', example: 'Quarry A' },
                endLocation: { type: 'string', example: 'Site B' },
                distance: { type: 'number', example: 120 },
                loadedQuantity: { type: 'number', example: 4200 },
                loadingStatus: { type: 'string', example: 'LOADED' },
                journeyStatus: { type: 'string', example: 'IN_TRANSIT' },
                journeyStatusUpdatedAt: { type: 'string', format: 'date-time' },
                actualFuelValue: { type: 'number', example: 48 },
                expectedFuelValue: { type: 'number', example: 45 },
                date: { type: 'string', format: 'date-time' },
                status: { type: 'string', example: 'active' },
                createdAt: { type: 'string', format: 'date-time' },
                journeySchedule: {
                  type: 'object',
                  nullable: true,
                  properties: {
                    id: { type: 'string', format: 'uuid' },
                    code: { type: 'string', example: 'JS-001' },
                  },
                },
              },
            },
          },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
    },
  },
};
