import variables from './variables.config.js';
import { ApiPaths } from '../docs/paths/api.paths.js';
import { ApiSchemas } from '../docs/schemas/api.schema.js';

export const swaggerSpec = {
  openapi: '3.0.0',
  info: {
    title: 'Construction ERP APIs',
    version: '1.0.0',
    description:
      'Interactive API documentation for all construction ERP endpoints.',
  },
  servers: [
    {
      url: variables.BASE_URL,
    },
  ],
  tags: [
    { name: 'Health' },
    { name: 'SuperAdmin' },
    { name: 'Domain Auth' },
    { name: 'User Auth' },
    { name: 'Domain Users' },
    { name: 'Roles' },
    { name: 'User Types' },
    { name: 'Domain User Types' },
    { name: 'Language' },
    { name: 'Vehicles' },
    { name: 'Inventory' },
    { name: 'Journey Schedules' },
    { name: 'Dispatch' },
    { name: 'App Errors' },
    { name: 'Modules' },
    { name: 'Permissions' },
    { name: 'Module Dependencies' },
    { name: 'Module Permissions' },
    { name: 'Products' },
    { name: 'Product Grades' },
    { name: 'Domain Last Purchase Rates' },
    { name: 'User Last Purchase Rates' },
    { name: 'Product UOMs' },
    { name: 'UOMs' },
    { name: 'Project User Roles' },
    { name: 'Raw Material Purchase Requests' },
    { name: 'Domain Projects' },
    { name: 'Domain Project Stages' },
    { name: 'Domain Project Tasks' },
    { name: 'Domain Project Task Delays' },
    { name: 'User Projects' },
    { name: 'User Project Stages' },
    { name: 'User Project Tasks' },
    { name: 'User Project Task Delays' },
    { name: 'Machinery' },
    { name: 'Machine Reading' },
    { name: 'Domain Currency' },
    { name: 'User Currency' },
    { name: 'Logs' },
    { name: 'Vendor Product Prices' },
    { name: 'User Vendor Product Prices' },
    { name: 'Admin Industry Role Templates' },
    { name: 'Payment Requests' },
    { name: 'User Payment Requests' },
    { name: 'Reports' },
    { name: 'Fuel Logs' },
    { name: 'User Fuel Logs' },
    { name: 'Domain Customers' },
    { name: 'User Customers' },
    { name: 'Domain Customer Rates' },
    { name: 'User Customer Rates' },
    { name: 'Domain Sale Orders' },
    { name: 'User Sale Orders' },
    { name: 'Domain Weigh Bridges' },
    { name: 'User Weigh Bridges' },
    { name: 'Domain Account Categories' },
    { name: 'User Account Categories' },
    { name: 'Domain Accounts' },
    { name: 'User Accounts' },
    { name: 'Domain Cost Centers' },
    { name: 'User Cost Centers' },
    { name: 'Domain General Ledger' },
    { name: 'User General Ledger' },
    { name: 'Domain Account Balances' },
    { name: 'User Account Balances' },
    { name: 'Alerts' },
    { name: 'User Alerts' },
    { name: 'Notifications' },
    { name: 'User Notifications' },
    { name: 'User Reports' },
  ],
  paths: {
    ...ApiPaths,
  },
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      },
    },
    schemas: {
      ...ApiSchemas,
    },
  },
};
