import { Router } from 'express';

import authRouter from './auth/auth.router.js';
import languageRouter from './language/language.router.js';
import currencyRouter from './currency/currency.router.js';
import locationRouter from './location/location.routes.js';
import mediaRouter from './media/media.routes.js';
import profileRouter from './profile/profile.router.js';
import userListRouter from './user/user.router.js';
import projectRouter from './project/project.router.js';
import projectStageRouter from './projectStage/projectStage.routes.js';
import projectUserAssignmentRouter from './projectUserAssignment/projectUserAssignment.routes.js';
import projectUserDailyLogRouter from './projectUserDailyLog/projectUserDailyLog.routes.js';
import projectTaskRouter from './projectTask/projectTask.routes.js';
import projectTaskImagesRouter from './projectTaskImages/projectTaskImages.routes.js';
import projectTaskDelayRouter from './projectTaskDelay/projectTaskDelay.routes.js';
import userTaskSubmissionRouter from './userTaskSubmission/userTaskSubmission.routes.js';
import machineryRouter from './machinery/machinery.routes.js';
import machineReadingRouter from './machineReading/machineReading.routes.js';
import maintenanceScheduleRouter from './maintenanceSchedule/maintenanceSchedule.routes.js';
import maintenanceLogRouter from './maintenanceLog/maintenanceLog.routes.js';
import maintenanceReportRouter from './maintenanceReport/maintenanceReport.routes.js';
import movementLogRouter from './movementLog/movementLog.routes.js';
import fuelLogRouter from './fuelLog/fuelLog.routes.js';
import inventoryFuelStockRouter from './inventoryFuelStock/inventoryFuelStock.routes.js';
import movementReportRouter from './movementReport/movementReport.routes.js';
import grnRouter from './grn/grn.router.js';
import productRouter from './product/product.router.js';
import vendorProductPriceRouter from './vendorProductPrice/vendorProductPrice.router.js';
import vendorRouter from './vendor/vendor.router.js';
import { uomRouter } from './uom/uom.router.js';
import authMiddleware from '../../middlewares/auth.js';
import modulePermissionRouter from './modulePermission/modulePermission.router.js';
import moduleRouter from './module/module.router.js';
import inventoryRouter from './inventory/inventory.router.js';
import invoiceRouter from './invoice/invoice.router.js';
import rawMaterialPurchaseRequestRouter from './rawMaterialPurchaseRequest/rawMaterialPurchaseRequest.router.js';
import appErrorRouter from './appError/appError.router.js';
import dispatchRouter from './dispatch/dispatch.router.js';
import journeyScheduleRouter from './journeySchedule/journeySchedule.router.js';
import vehicleRouter from './vehicle/vehicle.router.js';
import roleRouter from './role/role.router.js';
import onboardingRouter from './onboarding/onboarding.router.js';

import { allGradesRouter } from './productGrade/productGrade.router.js';
import { productGradeLastPurchaseRateRouter } from './productGradeLastPurchaseRate/productGradeLastPurchaseRate.router.js';
import paymentRequestRouter from './paymentRequest/paymentRequest.router.js';
import customerRouter from './customer/customer.router.js';
import customerRateRouter from './customerRate/customerRate.router.js';
import saleOrderRouter from './saleOrder/saleOrder.router.js';
import weighBridgeRouter from './weighBridge/weighBridge.router.js';

const userRouter = Router();

userRouter.use('/auth', authRouter);
userRouter.use('/onboarding', onboardingRouter);

userRouter.use(authMiddleware);
userRouter.use('/language', languageRouter);
userRouter.use('/currency', currencyRouter);
userRouter.use('/locations', locationRouter);
userRouter.use('/media', mediaRouter);
userRouter.use('/profile', profileRouter);
userRouter.use('/users', userListRouter);
userRouter.use('/projects', projectRouter);
userRouter.use('/project-stages', projectStageRouter);
userRouter.use('/project-user-assignments', projectUserAssignmentRouter);
userRouter.use('/project-user-daily-logs', projectUserDailyLogRouter);
userRouter.use('/project-tasks', projectTaskRouter);
userRouter.use('/project-task-images', projectTaskImagesRouter);
userRouter.use('/project-task-delays', projectTaskDelayRouter);
userRouter.use('/task-submission', userTaskSubmissionRouter);
userRouter.use('/machineries', machineryRouter);
userRouter.use('/machine-reading', machineReadingRouter);
userRouter.use('/maintenance-schedules', maintenanceScheduleRouter);
userRouter.use('/maintenance-logs', maintenanceLogRouter);
userRouter.use('/maintenance-reports', maintenanceReportRouter);
userRouter.use('/movement-logs', movementLogRouter);
userRouter.use('/movement-reports', movementReportRouter);
userRouter.use('/fuel-logs', fuelLogRouter);
userRouter.use('/inventory-fuel-stocks', inventoryFuelStockRouter);
userRouter.use('/grn', grnRouter);
userRouter.use('/products', productRouter);
userRouter.use('/vendors', vendorProductPriceRouter);
userRouter.use('/vendors', vendorRouter);
userRouter.use('/uoms', uomRouter());
userRouter.use('/inventory', inventoryRouter);
userRouter.use('/invoices', invoiceRouter);
userRouter.use('/rmpr', rawMaterialPurchaseRequestRouter);
userRouter.use('/modules', moduleRouter);
userRouter.use('/module-permissions', modulePermissionRouter);
userRouter.use('/app-errors', appErrorRouter);
userRouter.use('/vehicles', vehicleRouter);
userRouter.use('/journey-schedules', journeyScheduleRouter);
userRouter.use('/dispatch', dispatchRouter);
userRouter.use('/roles', roleRouter);
userRouter.use('/payment-requests', paymentRequestRouter);
userRouter.use('/customers', customerRouter);
userRouter.use('/customer-rates', customerRateRouter);
userRouter.use('/sale-orders', saleOrderRouter);
userRouter.use('/weigh-bridges', weighBridgeRouter);
userRouter.use('/grades', allGradesRouter());
userRouter.use('/last-purchase-rates', productGradeLastPurchaseRateRouter());

export default userRouter;
