import { Router } from 'express';
import apiKeyRouter from './apiKey/apiKey.routes';
import machineReadingRouter from './machineReading/machineReading.routes';
import maintenanceLogRouter from './maintenanceLog/maintenanceLog.routes';
import maintenanceReportRouter from './maintenanceReport/maintenanceReport.routes';
import maintenanceScheduleRouter from './maintenanceSchedule/maintenanceSchedule.routes';
import movementLogRouter from './movementLog/movementLog.routes';
import fuelLogRouter from './fuelLog/fuelLog.routes';
import inventoryFuelStockRouter from './inventoryFuelStock/inventoryFuelStock.routes';
import machineryInventoryRouter from './machineryInventory/machineryInventory.routes';
import machineryInventoryLogRouter from './machineryInventoryLog/machineryInventoryLog.routes';
import alertRouter from './alert/alert.routes';
import notificationRouter from './notification/notification.routes';
import movementReportRouter from './movementReport/movementReport.routes';
import locationRouter from './location/location.routes';
import machineryRouter from './machinery/machinery.routes';
import mediaRouter from './media/media.routes';
import projectRouter from './project/project.routes';
import projectStageRouter from './projectStage/projectStage.routes';
import projectTaskDelayRouter from './projectTaskDelay/projectTaskDelay.routes';
import projectTaskImagesRouter from './projectTaskImages/projectTaskImages.routes';
import projectTaskRouter from './projectTask/projectTask.routes';
import projectUserAssignmentRouter from './projectUserAssignment/projectUserAssignment.routes';
import projectUserDailyLogRouter from './projectUserDailyLog/projectUserDailyLog.routes';
import appErrorRouter from './appError/appError.router.js';
import authRouter from './auth/auth.router.js';
import dispatchRouter from './dispatch/dispatch.router.js';
import inventoryRouter from './inventory/inventory.router.js';
import journeyScheduleRouter from './journeySchedule/journeySchedule.router.js';
import roleRouter from './role/role.router.js';
import userRouter from './user/user.router.js';
import vehicleRouter from './vehicle/vehicle.router.js';
import productRouter from './product/product.router.js';
import { uomRouter } from './uom/uom.router.js';
import profileRouter from './profile/profile.router.js';
import languageRouter from './language/language.router.js';
import currencyRouter from './currency/currency.router.js';
import rawMaterialPurchaseRequestRouter from './rawMaterialPurchaseRequest/rawMaterialPurchaseRequest.router.js';
import grnRouter from './grn/grn.router.js';
import vendorProductPriceRouter from './vendorProductPrice/vendorProductPrice.router.js';
import vendorRouter from './vendor/vendor.router.js';
import invoiceRouter from './invoice/invoice.router.js';
import paymentRequestRouter from './paymentRequest/paymentRequest.router.js';
import customerRouter from './customer/customer.router.js';
import customerRateRouter from './customerRate/customerRate.router.js';
import customerPaymentRouter from './customerPayment/customerPayment.router.js';
import fiscalYearRouter from './fiscalYear/fiscalYear.router.js';
import accountingPeriodRouter from './accountingPeriod/accountingPeriod.router.js';
import journalEntryRouter from './journalEntry/journalEntry.router.js';
import journalEntryLineRouter from './journalEntryLine/journalEntryLine.router.js';
import adminUserTypeRouter from './adminUserType/adminUserType.routes';
import saleOrderRouter from './saleOrder/saleOrder.router.js';
import weighBridgeRouter from './weighBridge/weighBridge.router.js';
import accountCategoryRouter from './accountCategory/accountCategory.router.js';
import accountRouter from './account/account.router.js';
import generalLedgerRouter from './generalLedger/generalLedger.router.js';
import accountBalanceRouter from './accountBalance/accountBalance.router.js';
import costCenterRouter from './costCenter/costCenter.router.js';
import reportRouter from './report/report.routes';
import authMiddleware from '../../middlewares/auth.js';
import isDomain from '../../middlewares/isDomain.js';
import moduleRouter from './module/module.router';
import modulePermissionRouter from './modulePermission/modulePermission.router';
import onboardingRouter from './onboarding/onboarding.router.js';
import dashboardRouter from './dashboard/dashboard.router.js';

import { allGradesRouter } from './productGrade/productGrade.router.js';
import { productGradeLastPurchaseRateRouter } from './productGradeLastPurchaseRate/productGradeLastPurchaseRate.router.js';

const domainRouter = Router();

// Routes that don't need domain auth globally
domainRouter.use('/auth', authRouter);
domainRouter.use('/onboarding', onboardingRouter);

// isDomain routes
domainRouter.use(authMiddleware);
domainRouter.use(isDomain);

domainRouter.use('/api-keys', apiKeyRouter);
domainRouter.use('/dashboard', dashboardRouter);
domainRouter.use('/media', mediaRouter);
domainRouter.use('/machineries', machineryRouter);
domainRouter.use('/machine-reading', machineReadingRouter);
domainRouter.use('/maintenance-logs', maintenanceLogRouter);
domainRouter.use('/maintenance-reports', maintenanceReportRouter);
domainRouter.use('/maintenance-schedules', maintenanceScheduleRouter);
domainRouter.use('/movement-logs', movementLogRouter);
domainRouter.use('/movement-reports', movementReportRouter);
domainRouter.use('/fuel-logs', fuelLogRouter);
domainRouter.use('/inventory-fuel-stocks', inventoryFuelStockRouter);
domainRouter.use('/machinery-inventory', machineryInventoryRouter);
domainRouter.use('/machinery-inventory-logs', machineryInventoryLogRouter);
domainRouter.use('/alerts', alertRouter);
domainRouter.use('/notifications', notificationRouter);
domainRouter.use('/locations', locationRouter);
domainRouter.use('/projects', projectRouter);
domainRouter.use('/project-stages', projectStageRouter);
domainRouter.use('/project-tasks', projectTaskRouter);
domainRouter.use('/project-task-images', projectTaskImagesRouter);
domainRouter.use('/project-task-delays', projectTaskDelayRouter);
domainRouter.use('/project-user-assignments', projectUserAssignmentRouter);
domainRouter.use('/project-user-daily-logs', projectUserDailyLogRouter);
domainRouter.use('/profile', profileRouter);
domainRouter.use('/roles', roleRouter);
domainRouter.use('/users', userRouter);
domainRouter.use('/inventory', inventoryRouter);
domainRouter.use('/app-errors', appErrorRouter);
domainRouter.use('/vehicles', vehicleRouter);
domainRouter.use('/journey-schedules', journeyScheduleRouter);
domainRouter.use('/dispatch', dispatchRouter);
domainRouter.use('/products', productRouter);
domainRouter.use('/uoms', uomRouter());
domainRouter.use('/language', languageRouter);
domainRouter.use('/currency', currencyRouter);
domainRouter.use('/rmpr', rawMaterialPurchaseRequestRouter);
domainRouter.use('/grn', grnRouter);
domainRouter.use('/vendors', vendorProductPriceRouter);
domainRouter.use('/vendors', vendorRouter);
domainRouter.use('/invoices', invoiceRouter);
domainRouter.use('/payment-requests', paymentRequestRouter);
domainRouter.use('/customers', customerRouter);
domainRouter.use('/customer-rates', customerRateRouter);
domainRouter.use('/customer-payments', customerPaymentRouter);
domainRouter.use('/fiscal-years', fiscalYearRouter);
domainRouter.use('/accounting-periods', accountingPeriodRouter);
domainRouter.use('/journal-entries', journalEntryRouter);
domainRouter.use('/journal-entry-lines', journalEntryLineRouter);
domainRouter.use('/admin-user-types', adminUserTypeRouter);
domainRouter.use('/sale-orders', saleOrderRouter);
domainRouter.use('/weigh-bridges', weighBridgeRouter);
domainRouter.use('/account-categories', accountCategoryRouter);
domainRouter.use('/accounts', accountRouter);
domainRouter.use('/general-ledger', generalLedgerRouter);
domainRouter.use('/account-balances', accountBalanceRouter);
domainRouter.use('/cost-centers', costCenterRouter);
domainRouter.use('/report', reportRouter);
domainRouter.use('/modules', moduleRouter);
domainRouter.use('/module-permissions', modulePermissionRouter);
domainRouter.use('/grades', allGradesRouter());
domainRouter.use('/last-purchase-rates', productGradeLastPurchaseRateRouter());

export default domainRouter;
