#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

echo "formatting code..."
npm run format

echo "fixing lint..."
npm run lint:fix
echo "running lint..."
npm run lint
echo "type checking..."
npm run typecheck
